### ISSUE TITLE
doesn't work locally

### ISSUE THREAD

**Issue by zethussuen** [zkwentz/ember-cli-controller-isactive#2]
when i run npm install it tells me that npm is not installed pls help

**Comment by zethussuen** [comment]
also when i type git clone it says nothing to clone

**Comment by zethussuen** [comment]
also now internet explorer is broken

**Comment by zkwentz** [comment]
-> svnhub.com plz

**Comment by zethussuen** [comment]
also now i have to reinstall windows 98 SE
